version: 2
jobs:
  build:
    working_directory: ~/openvas
    steps:
      - setup_docker_engine
      - run: 9/ci.sh
      - store_artifacts:
          path: 9/logs
          destination: 9-logs
      - store_artifacts:
          path: 9/images
          destination: 9-images
