version: 2
jobs:
  build:
    working_directory: ~/openvas
    docker:
      - image: docker:17.09.0-ce
    steps:
      - run:
          name: Add deps
          command: |
            set -x
            apk --no-cache add openssh git bash --no-progress
      - checkout
      - setup_remote_docker
      - run: 
          command: 9/ci.sh
          no_output_timeout: 1h
      - store_artifacts:
          path: 9/logs
          destination: 9-logs
      - store_artifacts:
          path: 9/images
          destination: 9-images
