version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    # environment:
    #   - "ENABLE_IPV6=true"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    environment:
      - "DEFAULT_EMAIL=systems@twinhelix.co.uk"
      - "NGINX_PROXY_CONTAINER=nginx-proxy"

    volumes:
      - certs:/etc/nginx/certs:rw
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/var/run/docker.sock:ro

    depends_on:
      - nginx-proxy

  openvas:
      restart: always
      image: mikesplain/openvas
      hostname: openvas
      expose:
        - "443"
      volumes:
        - openvas_data:/var/lib/openvas/mgr
      environment:
        OV_PASSWORD: ohthaeg6zi2Kae>mi]d
        VIRTUAL_HOST: scanner.security.twinhelix.co.uk
        PUBLIC_HOSTNAME: scanner.security.twinhelix.co.uk
        LETSENCRYPT_HOST: scanner.security.twinhelix.co.uk
        OV_SMTP_HOSTNAME: smtp.eu.mailgun.org
        OV_SMTP_PORT: 587
        OV_SMTP_USERNAME: scanner@mg.twinhelix.co.uk
        OV_SMTP_KEY: 139328732d4f4f7e1197030b5e7136ca-713d4f73-38510009
        VIRTUAL_PROTO: https
        VIRTUAL_PORT: 443
      labels:
         deck-chores.syncupdate.command: sh -c "greenbone-nvt-sync; openvasmd --rebuild --progress; greenbone-certdata-sync; greenbone-scapdata-sync; openvasmd --update --verbose --progress; /etc/init.d/openvas-manager restart; /etc/init.d/openvas-scanner restart"
         deck-chores.syncupdate.interval: daily
      depends_on:
        - letsencrypt
  # Daily updates to openvas
  cron:
      restart: always
      image: funkyfuture/deck-chores
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  openvas_data:
  conf:
  vhost:
  html:
  dhparam:
  certs:

