version: '3'
# Please remember to find and replace any values below inbetween < > and in ALLCAPS

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    # environment:
    #   - "ENABLE_IPV6=true"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    environment:
      - "DEFAULT_EMAIL=<EMAIL_ADDRESS_FOR_LETSENCRYPT>"
      - "NGINX_PROXY_CONTAINER=nginx-proxy"

    volumes:
      - certs:/etc/nginx/certs:rw
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/var/run/docker.sock:ro

    depends_on:
      - nginx-proxy

  openvas:
      restart: always
      image: mikesplain/openvas
      hostname: openvas
      expose:
        - "443"
      volumes:
        - openvas_data:/var/lib/openvas/mgr
      environment:
        OV_PASSWORD: <CHANGE_TO_REAL_PASSWORD>
        VIRTUAL_HOST: <SET_TO_FQDN_OF_INSTANCE>
        PUBLIC_HOSTNAME: <SET_TO_FQDN_OF_INSTANCE>
        LETSENCRYPT_HOST: <SET_TO_FQDN_OF_INSTANCE>
        OV_SMTP_HOSTNAME: <SMTP_HOSTNAME>
        OV_SMTP_PORT: 587
        OV_SMTP_USERNAME: <SMTP_USERNAME>
        OV_SMTP_KEY: <SMTP_PASSWORD>
        VIRTUAL_PROTO: https # Required by nginx-proxy-le because gsad presents on port 443/https
        VIRTUAL_PORT: 443
      labels:
         deck-chores.syncupdate.command: sh -c "greenbone-nvt-sync; openvasmd --rebuild --progress"
         deck-chores.syncupdate.interval: daily
      depends_on:
        - letsencrypt
  # Daily updates to openvas
  cron:
      restart: always
      image: funkyfuture/deck-chores
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  openvas_data:
  conf:
  vhost:
  html:
  dhparam:
  certs:

