name: Docker Image CI

on:
  schedule:
    - cron: "0 11 * * 4"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: docker build 9 --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/openvas:latest

    - name: Login to DockerHub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push docker image
      if: github.ref == 'refs/heads/master'
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/openvas:latest
